import React from 'react';
import { Bell, AlertCircle, Clock, ShieldAlert } from 'lucide-react';

const ServiceNotifications = () => {
  const notifications = [
    { id: 1, type: 'critical', title: 'Delivery Risk: Order #10452', msg: 'Delivery date is tomorrow and service is still pending vendor assignment.', time: '10 mins ago', icon: ShieldAlert },
    { id: 2, type: 'warning', title: 'Vendor Delay Alert', msg: 'Vendor "ABC Printing" missed expected completion for Order #10444.', time: '1 hour ago', icon: AlertCircle },
    { id: 3, type: 'info', title: 'New Service Queued', msg: 'Order #10460 transferred from Production.', time: '2 hours ago', icon: Bell },
    { id: 4, type: 'warning', title: 'Labour Shortage', msg: 'Only 2 installers available tomorrow vs 5 required.', time: '3 hours ago', icon: AlertCircle }
  ];

  return (
    <div className="p-8 max-w-4xl mx-auto animate-in fade-in">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-black text-slate-900">Notifications & Escalations</h1>
          <p className="text-slate-500 mt-1">System alerts generated by the Delivery KPI Engine.</p>
        </div>
        <button className="text-sm font-semibold text-blue-600 hover:text-blue-700">Mark all read</button>
      </div>

      <div className="bg-white border rounded-2xl shadow-sm overflow-hidden">
        <div className="divide-y">
          {notifications.map(n => (
            <div key={n.id} className="p-5 flex gap-4 hover:bg-slate-50 transition-colors">
              <div className={`mt-1 shrink-0 w-10 h-10 rounded-full flex items-center justify-center ${
                n.type === 'critical' ? 'bg-red-100 text-red-600' :
                n.type === 'warning' ? 'bg-amber-100 text-amber-600' :
                'bg-blue-100 text-blue-600'
              }`}>
                <n.icon className="w-5 h-5" />
              </div>
              <div className="flex-1">
                <div className="flex justify-between items-start">
                  <h4 className="font-bold text-slate-800">{n.title}</h4>
                  <span className="text-xs font-semibold text-slate-400">{n.time}</span>
                </div>
                <p className="text-sm text-slate-600 mt-1">{n.msg}</p>
                {n.type === 'critical' && (
                  <button className="mt-3 px-3 py-1.5 bg-red-50 text-red-700 hover:bg-red-100 rounded text-xs font-bold border border-red-200">
                    Take Action
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ServiceNotifications;
